builds:
  - binary: askcloudhelloworld
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: askcloudhelloworld
    homepage: https://github.com/askcloudarchitech/askcloudhelloworld
    tap:
      owner: askcloudarchitech
      name: homebrew-askcloudarchitech
    commit_author:
      name: gmorse81
      email: gmorse81@gmail.com

checksum:
  name_template: 'checksums.txt'